## Import and load Datasets

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
dataset_paths = {'customers' : '../data/olist_customers_dataset.csv',
"geolocation" : "../data/olist_geolocation_dataset.csv",
"order_items" : "../data/olist_order_items_dataset.csv",
"order_payments" : '../data/olist_order_payments_dataset.csv',
"order_reviews" : '../data/olist_order_reviews_dataset.csv',
"orders" : '../data/olist_orders_dataset.csv',
"products" : '../data/olist_products_dataset.csv',
"sellers" : '../data/olist_sellers_dataset.csv',
"product_category" : '../data/product_category_name_translation.csv'}

In [ ]:
# Load dataset

def load_dataset():

    data = {}
    for key in dataset_paths:
         data[key]= pd.read_csv(dataset_paths[key])

    return data

data = load_dataset()

In [52]:
df = data['orders'].merge(data['order_items'], on='order_id', how='inner')
df = df.merge(data['order_payments'], on='order_id', how='inner')
df = df.merge(data['order_reviews'], on='order_id', how='inner')
df = df.merge(data['products'], on='product_id', how='inner')
df = df.merge(data['customers'], on='customer_id', how='inner')
df = df.merge(data['sellers'], on='seller_id', how='inner')

In [53]:
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,product_length_cm,product_height_cm,product_width_cm,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,seller_zip_code_prefix,seller_city,seller_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,87285b34884572647811a353c7ac498a,...,19.0,8.0,13.0,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350,maua,SP
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,87285b34884572647811a353c7ac498a,...,19.0,8.0,13.0,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350,maua,SP
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,87285b34884572647811a353c7ac498a,...,19.0,8.0,13.0,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350,maua,SP
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1,595fac2a385ac33a80bd5114aec74eb8,...,19.0,13.0,19.0,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,31570,belo horizonte,SP
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1,aa4383b373c6aca5d8797843e5594415,...,24.0,19.0,21.0,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,14840,guariba,SP

In [54]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 117329 entries, 0 to 117328
Data columns (total 39 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       117329 non-null  str
 1   customer_id                    117329 non-null  str
 2   order_status                   117329 non-null  str
 3   order_purchase_timestamp       117329 non-null  str
 4   order_approved_at              117314 non-null  str
 5   order_delivered_carrier_date   116094 non-null  str
 6   order_delivered_customer_date  114858 non-null  str
 7   order_estimated_delivery_date  117329 non-null  str
 8   order_item_id                  117329 non-null  int64
 9   product_id                     117329 non-null  str
 10  seller_id                      117329 non-null  str
 11  shipping_limit_date            117329 non-null  str
 12  price                          117329 non-null  float64
 13  freight_value                  117329 non-null  float64
 14  payment_sequential             117329 non-null  int64
 15  payment_type                   117329 non-null  str
 16  payment_installments           117329 non-null  int64
 17  payment_value                  117329 non-null  float64
 18  review_id                      117329 non-null  str
 19  review_score                   117329 non-null  int64
 20  review_comment_title           13892 non-null   str
 21  review_comment_message         49679 non-null   str
 22  review_creation_date           117329 non-null  str
 23  review_answer_timestamp        117329 non-null  str
 24  product_category_name          115634 non-null  str
 25  product_name_lenght            115634 non-null  float64
 26  product_description_lenght     115634 non-null  float64
 27  product_photos_qty             115634 non-null  float64
 28  product_weight_g               117309 non-null  float64
 29  product_length_cm              117309 non-null  float64
 30  product_height_cm              117309 non-null  float64
 31  product_width_cm               117309 non-null  float64
 32  customer_unique_id             117329 non-null  str
 33  customer_zip_code_prefix       117329 non-null  int64
 34  customer_city                  117329 non-null  str
 35  customer_state                 117329 non-null  str
 36  seller_zip_code_prefix         117329 non-null  int64
 37  seller_city                    117329 non-null  str
 38  seller_state                   117329 non-null  str
dtypes: float64(10), int64(6), str(23)
memory usage: 34.9 MB

In [56]:
df.isna().sum()

order_id                              0
customer_id                           0
order_status                          0
order_purchase_timestamp              0
order_approved_at                    15
order_delivered_carrier_date       1235
order_delivered_customer_date      2471
order_estimated_delivery_date         0
order_item_id                         0
product_id                            0
seller_id                             0
shipping_limit_date                   0
price                                 0
freight_value                         0
payment_sequential                    0
payment_type                          0
payment_installments                  0
payment_value                         0
review_id                             0
review_score                          0
review_comment_title             103437
review_comment_message            67650
review_creation_date                  0
review_answer_timestamp               0
product_category_name              1695
product_name_lenght                1695
product_description_lenght         1695
product_photos_qty                 1695
product_weight_g                     20
product_length_cm                    20
product_height_cm                    20
product_width_cm                     20
customer_unique_id                    0
customer_zip_code_prefix              0
customer_city                         0
customer_state                        0
seller_zip_code_prefix                0
seller_city                           0
seller_state                          0
dtype: int64

In [58]:
df['order_purchase_timestamp']

0         2017-10-02 10:56:33
1         2017-10-02 10:56:33
2         2017-10-02 10:56:33
3         2018-07-24 20:41:37
4         2018-08-08 08:38:49
                 ...
117324    2018-02-06 12:58:58
117325    2017-08-27 14:46:43
117326    2018-01-08 21:28:27
117327    2018-01-08 21:28:27
117328    2018-03-08 20:57:30
Name: order_purchase_timestamp, Length: 117329, dtype: str

In [60]:
# Ensure timestamps are in datetime format
df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'])
df['order_delivered_customer_date'] = pd.to_datetime(df['order_delivered_customer_date'])

# Create useful features from order_purchase_timestamp
df['day_of_week_int'] = df['order_purchase_timestamp'].dt.weekday + 1  # Day of week as integer (1 = Monday, etc.)
df['hour'] = df['order_purchase_timestamp'].dt.hour                    # Hour of day
df['month'] = df['order_purchase_timestamp'].dt.month                  # Month as integer
df['year'] = df['order_purchase_timestamp'].dt.year                    # Year as integer
df['date'] = df['order_purchase_timestamp'].dt.to_period('M')          # Monthly period for time series analysis

# Calculate delivery time in days
df['delivery_time'] = (df['order_delivered_customer_date'] - df['order_purchase_timestamp']).dt.days

df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,customer_state,seller_zip_code_prefix,seller_city,seller_state,day_of_week_int,hour,month,year,date,delivery_time
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,87285b34884572647811a353c7ac498a,...,SP,9350,maua,SP,1,10,10,2017,2017-10,8.0
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,87285b34884572647811a353c7ac498a,...,SP,9350,maua,SP,1,10,10,2017,2017-10,8.0
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1,87285b34884572647811a353c7ac498a,...,SP,9350,maua,SP,1,10,10,2017,2017-10,8.0
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1,595fac2a385ac33a80bd5114aec74eb8,...,BA,31570,belo horizonte,SP,2,20,7,2018,2018-07,13.0
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1,aa4383b373c6aca5d8797843e5594415,...,GO,14840,guariba,SP,3,8,8,2018,2018-08,9.0

In [61]:
# Renaming the column to correct the spelling
df.rename(columns={'product_name_lenght': 'product_name_length'}, inplace=True)

## Exploratory Data Analysis